# 1. PyTorch Basics: Tensors & Gradients

이 시리즈의 첫번째 파트에서는 다음과 같은 항목을 다룹니다.

* PyTorch Tensor 소개
* Tensor 연산 및 gradients
* PyTorch와 Numpy 간의 상호 운용성
* PyTorch 문서 사이트를 사용하는 방법

----------------------------------------------------------------------------------------------------------------------------------------

파이토치를 시작하기 위해 torch 모듈을 임포트합니다. (설치는 완료되어 있다고 가정하고 진행합니다.)
해당 문서는 pytorch 1.7.1 버전을 사용합니다.

In [1]:
import torch

## Tensors

- 파이토치는 텐서를 처리하기 위한 라이브러리입니다.
- 텐서는 숫자, 벡터, 행렬 또는 n차원 배열입니다. 

단일 숫자로 텐서를 생성해 보겠습니다.

In [2]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

4.는 4.0의 줄임말입니다. 파이썬(또는 파이토치)에서 부동 소수점 숫자를 생성하는데 사용됩니다. 텐서의 데이터 타입(dtype) 속성을 통해서 이를 확인할 수 있습니다.

In [3]:
t1.dtype

torch.float32

조금 더 복잡한 텐서를 만들어 봅시다.

In [5]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [6]:
# Matric
t3 = torch.tensor([[5., 6],
                   [7, 8],
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
# 3-dimensional array
t4 = torch.tensor([ 
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19]]])
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

텐서는 여러 차원과 각 차원마다 다른 길이를 가질 수 있습니다. 텐서의 .shape 속성을 사용하여 각 차원의 길이를 검사할 수 있습니다.

In [8]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [9]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [10]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [11]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])


torch.Size([2, 2, 3])

주의 : 부적절한 모양으로 텐서를 생성하는 것은 불가능합니다.

In [ ]:
t5 = torch.tensor([[5., 6, 11],
                   [7, 8],
                   [9, 10]])
t5

행 [5., 6, 11] 및 [7, 8]의 길이가 일치하지 않기 때문에 ValueError가 발생합니다.

----------------------------------------------------------------------------------------------------------------------------------------

## Tensor operations and gradients

- 텐서들에 일반적인 산술 연산을 할 수 있습니다.

In [19]:
# 텐서는 다음과 같이 required_grad=True로 생성할 수 있습니다.
# torch.autograd는 자동 미분을 위해 연산을 기록합니다.

x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

세 개의 텐서를 만들었습니다. x, w, b는 모두 숫자입니다. w 및 b에는 추가 매개변수 requires_grad 가 True 로 설정되어 있습니다. 우리는 잠시 후에 그것이 무엇을 하는지 볼 것입니다. 이 텐서를 결합하여 새로운 텐서 y를 생성해 보겠습니다.

In [20]:
# Arithmetic operations 
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
y는 값이 3 * 4 + 5 = 17인 텐서입니다. 파이토치를 고유하게 만드는 것은 require_grad 가 True 로 설정된 텐서, 
즉 w 및 b에 대한 y의 미분들을 자동으로 계산할 수 있다는 것입니다. 파이토치의 이 기능을 autograd(자동 그라디언트)라고 합니다.

미분을 계산하기 위해 결과 y에 대해 .backward 메서드를 호출할 수 있습니다.

In [21]:
# Compute derivatives
y.backward()

입력 텐서에 대한 y의 미분은 각 텐서의 .grad 속성에 저장됩니다.

In [23]:
# Display gradients
print(f'dy/dx: {x.grad}')
print(f'dy/dw: {w.grad}')
print(f'dy/db: {b.grad}')

dy/dx: None
dy/dw: 3.0
dy/db: 1.0


예상대로 dy/dw는 x와 동일한 값, 즉 3을 가지며 dy/db는 1의 값을 갖습니다. x에 require_grad가 True로 설정되어 있지 않기 때문에 x.grad는 None입니다.

w.grad의 "grad"는 미분의 또 다른 용어인 gradient의 약자입니다. gradient라는 용어는 벡터와 행렬을 다룰 때 주로 사용됩니다.

----------------------------------------------------------------------------------------------------------------------------------------

#### 짤막한 예시

In [2]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [13]:
out = z.mean()
out.backward()

print(f'dout/dz: {z.grad}')
print(f'dout/dy: {y.grad}')
print(f'dout/dx: {x.grad}')

dout/dz: None
dout/dy: None
dout/dx: tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


<ipython-input-13-2672fe1dd3fd>:4: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(f'dout/dz: {z.grad}')
<ipython-input-13-2672fe1dd3fd>:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(f'dout/dy: {y.grad}')


y와 z는 is_leaf가 False라서 y.grad와 z.grad에 Gradient가 저장되지 않습니다. 

만약에 is_leaf가 아닌 Tensor에 Gradient가 grad에 저장되게 하고 싶으면, 
해당 Tensor의 retain_grad()를 호출해서 retains_grad를 True로 설정하고, backward()를 호출하면 grad에 저장됩니다.

In [3]:
y.retain_grad()
z.retain_grad()
out = z.mean()
out.backward(retain_graph=True)

print(f'dout/dz: {z.grad}')
print(f'dout/dy: {y.grad}')
print(f'dout/dx: {x.grad}')

dout/dz: tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
dout/dy: tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
dout/dx: tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


다음 get_tensor_info 함수에서 텐서의 요소들을 살펴볼 수 있습니다.

In [4]:
def get_tensor_info(tensor):
    info = []
    for name in ['requires_grad', 'is_leaf', 'retains_grad', 'grad_fn', 'grad']:
        info.append(f'{name}({getattr(tensor, name, None)})')
    info.append(f'tensor({str(tensor)})')
    return ' '.join(info)

print(f'x: {get_tensor_info(x)}')

x: requires_grad(True) is_leaf(True) retains_grad(None) grad_fn(None) grad(tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])) tensor(tensor([[1., 1.],
        [1., 1.]], requires_grad=True))


----------------------------------------------------------------------------------------------------------------------------------------

## Tensor functions

산술 연산 외에도 torch 모듈에는 텐서를 생성하고 조작하기 위한 많은 함수들이 포함되어 있습니다. 몇 가지 예를 살펴보겠습니다.

In [24]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3,2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [25]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [26]:
# Compute the sin() of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [27]:
# Change the shape of a tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

----------------------------------------------------------------------------------------------------------------------------------------

## Interoperability with Numpy

Numpy는 Python에서 수학 및 과학 컴퓨팅에 사용되는 인기 있는 오픈 소스 라이브러리입니다. 대규모 다차원 배열에서 효율적인 작업을 가능하게 하며 다음을 포함하는 지원 라이브러리의 방대한 에코시스템을 갖추고 있습니다.

* 파일 I/O 및 데이터 분석을 위한 Pandas
* 플로팅 및 시각화를 위한 Matplotlib
* 이미지 및 비디오 처리를 위한 OpenCV

Python의 Numpy 및 기타 데이터 과학 라이브러리에 대해 자세히 알아보려면 https://jovian.ai/aakashns/python-numerical-computing-with-numpy 튜토리얼 시리즈를 확인하세요.


텐서는 torch.tensor() 생성자를 사용하여 Python list 또는 numpy array로부터 생성할 수 있습니다. 하지만 list와 array는 근본적인 차이가 있어 주의해야합니다.

### python list
다른 데이터 타입을 포함할 수 있습니다. (예: a = ['hi', 6, 8] )
list들 간에 산술연산을 수행할 수 없습니다.
list 안에 다양한 크기의 list를 담을 수 있습니다. (예: b = ['j', [1,2,3], 'hello'] )

### numpy array
같은 데이터 타입만을 포함할 수 있습니다. (예: a = numpy.array([1, 2, 3]) )
array 들 간에 산술연산을 수행할 수 있습니다.
array 안에 포함된 array 들은 동일한 크기여야 합니다. (b = numpy.array([[1,2],[3,4]]) )

Python에서 list 를 만드는 방법과 이를 텐서로 변형하는 방법은 다음과 같습니다.

In [17]:
a =[[1., -1], [1, -1]]
a

[[1.0, -1], [1, -1]]

In [18]:
at = torch.tensor([[1., -1], [1, -1]])
at

tensor([[ 1., -1.],
        [ 1., -1.]])

Numpy에서 배열을 만드는 방법과 이를 텐서로 변형하는 방법은 다음과 같습니다.

In [19]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [20]:
b = torch.tensor(np.array([[1, 2], [3, 4]]))
b

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

torch.from_numpy를 사용하여 Numpy 배열을 PyTorch 텐서로 변환할 수 있습니다.

In [21]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

numpy 배열과 torch 텐서의 데이터 유형이 유사한지 확인하겠습니다.

In [22]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

텐서의 .numpy 메서드를 사용하여 PyTorch 텐서를 Numpy 배열로 변환할 수 있습니다.

In [23]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

PyTorch와 Numpy간의 상호 운용성은 작업할 대부분의 데이터 세트가 Numpy 배열로 읽고 사전 처리될 가능성이 높기 때문에 필수적입니다.

Numpy는 이미 다차원 숫자 데이터 작업을 위한 데이터 구조와 유틸리티를 제공하기 때문에 PyTorch와 같은 라이브러리가 필요한 이유가 궁금할 것입니다. 두 가지 주요 이유가 있습니다.

1. Autograd: 텐서 연산의 미분을 자동으로 계산하는 기능은 딥 러닝 모델을 훈련하는 데 필수적입니다.
2. GPU 지원: 대규모 데이터 세트 및 대규모 모델로 작업하는 동안 PyTorch 텐서 작업은 GPU(그래픽 처리 장치)를 사용하여 효율적으로 수행할 수 있습니다. 일반적으로 몇 시간이 걸릴 수 있는 계산을 GPU를 사용하면 몇 분 안에 완료할 수 있습니다.

이 시리즈에서 PyTorch의 이러한 두 기능을 광범위하게 활용할 것입니다.

----------------------------------------------------------------------------------------------------------------------------------------